<a href="https://colab.research.google.com/github/AlexeySergeychuk/GB-Python/blob/main/dz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY


**Задание 1**

In [ ]:
import numpy as np


In [ ]:
a1 = np.array([1,2,3,3,1]).reshape(5,1)
a2 = np.array([6,8,11,10,7]).reshape(5,1)

In [ ]:
a = np.concatenate((a1, a2), axis=1)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

**Задание 2**

In [ ]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**


In [ ]:
a_sentered_sp = np.dot(a_centered[:,0], a_centered[:, 1])
a_sentered_sp

8.0

In [ ]:
a.shape

(5, 2)

In [ ]:
a_sentered_sp / (5-1)

2.0

**Задание 4**

In [ ]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

#Pandas

**Задание 1**

In [20]:
import pandas as pd

In [21]:
authors = pd.DataFrame({'author_id': [1,2,3], 'author_name': ['Тургенев', 'Чехов','Островский']},
                       columns= ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [23]:
book = pd.DataFrame({'author_id': [1,1,1,2,2,3,3], 
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]},
                    columns=['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

**Задание 2**

In [24]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3**

In [25]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

**Задание 4**

In [29]:
authors_stat = authors_price.groupby('author_name').agg({'price': 'min', 'price': 'max', 'price': 'mean'}, columns=['price_min', 'price_max', 'price_mean'])
authors_stat

price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [31]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean')
authors_stat

SyntaxError: ignored

In [37]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean'])
authors_stat

min  max        mean
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000

In [40]:
 authors_stat = authors_stat.rename(columns={'min' : 'min_price', 'max': 'max_price', 'mean': 'mean_price'})
 authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

**Задание 5**

In [42]:
somelist = ['твердая', 'мягкая', "мягкая", "твердая", "твердая", "мягкая", "мягкая"]
somelist

['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [43]:
authors_price['cover'] = somelist
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [44]:
?pd.pivot_table

In [48]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns=['cover'], aggfunc=np.sum, fill_value=0 )
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [49]:
pd.to_pickle(book_info, 'book_info.pkl')

In [52]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [53]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True